### ISSUE TITLE
Song line should be in blockquote with appropriate semantics

### ISSUE THREAD

**Issue by drgrigg** [mgbennet/p-g-wodehouse_mike#1]
"Auntie went to Aldershot in a Paris pom-pom hat" in chapter 5: I think this would be better inside a blockquote with the `epub:type="z3998:song"` semantic rather than being italicised with `<em>` tags as it's not emphasised speech.

**Comment by mgbennet** [comment]
I asked about this earlier in the thread and Alex said that `<em>` was fine. I'm a little leery of putting the lyrics in blockquotes, as I think it sort of interrupts the flow of the page, and the song is sort of background music to what's going on in the scene. [In the scans](https://archive.org/details/mikepublicschool00wodeuoft/page/30/mode/1up), it's inline. If you feel strongly about it I can change it but I'm not sure it's better in this case.

**Comment by drgrigg** [comment]
OK, that’s fine then.
