### ISSUE TITLE
Some [Editorial] commits don't need to be editorial

### ISSUE THREAD

**Issue by drgrigg** [mgbennet/p-g-wodehouse_mike#2]
Our policy with [Editorial] commits needs to be clarified. This is is a current and active debate on the forum.

It's good that you've made 'atomic' commits with a small number of changes in each.

However, as I _currently_ understand our policy, I think commit 79f5420 "[Editorial] Fix several typos in the scans that lint caught." doesn't need to be [Editorial] because as the message says, it's fixing typos, which we don't generally regard as an editorial change.

Similarly I don't think commit d00d363 "[Editorial] Times to use colon" doesn't need to be [Editorial] because this is a styling issue which doesn't alter the source in a substantial way.

If you disagree, we'll need to ask Alex for confirmation.

These are easy fixes with an interactive rebase.

**Comment by drgrigg** [comment]
Only the commit messages need to be altered, just to clarify.

**Comment by mgbennet** [comment]
I was following the Step by Step Guide's tip, which states "Editorial changes are those where we make an editorial decision to alter the original text, for example modernizing spelling or _fixing a probable printer’s typo_." The fixes in 79f5420 were all typos present in the original scans, so I thought it was appropriate to mark them as editorial; same with changing the times to use colon.

As you say, though, these changes aren't altering the source in a substantial way. I'll bring it up on the forum.

**Comment by drgrigg** [comment]
Leave them as is, then.
