### ISSUE TITLE
Short description in content.opf needs to be more generic

### ISSUE THREAD

**Issue by drgrigg** [mgbennet/p-g-wodehouse_mike#3]
We try to make our short descriptions generic and not include character names.

So you could make it:

`A boy’s adventures in public school are filled with cricket, colorful characters, and a great deal of fun at the expense of authoritarian school masters.`

**Comment by drgrigg** [comment]
Also, there's a typo in the long description:

`memoriable` should be `memorable`.

**Comment by mgbennet** [comment]
Fixed.
