### ISSUE TITLE
Epubcheck errors on build

### ISSUE THREAD

**Issue by drgrigg** [mgbennet/p-g-wodehouse_mike#5]
epub-type used instead of epub:type.

There are a number of such instances. This came up when I tried to do a build, I'm not sure why you wouldn't have seen them.

Similarly xml:type was used in a couple of spots rather than epub:type.

There's also an epub check error thrown about the table in chapter 40.

**Comment by mgbennet** [comment]
Fixed the stupidity for epub-type and xml:type... that's what I get for hurrying and not checking things before I check them in. 

I'm not seeing any epubcheck errors for chapter 40. That's with epubcheck 4.2.6. What's the error?

**Comment by drgrigg** [comment]
I get this error: "vnu failed". I have no idea what vnu is!

chapter-40.xhtml(137:7) │ A table row was 1 columns wide, which is less than the column count established by the first row (2).

**Comment by mgbennet** [comment]
I added an empty <td> to the last row to satisfy that error message. I have no idea what "VNU failed" means either! But I don't get it when I run it, so not sure what to do about it.
